### ISSUE TITLE
Mode-responsive icons

### ISSUE THREAD

**Issue by kvistgaard** [rcvd/magic-tags#2]
Currently, if I pick black color for an icon,  would expect it to be white in dark mode and so on, for other selections.
One way to do that would be to have separate section for per mode but that would be too much.  I'd prefer if the colors are already paired so selecting one for a mode to automatically select a corresponding one for the alternative mode.

**Comment by rcvd** [comment]
I've already implemented this for all colors except black and white. Inverting black and white is implemented for the next release.

**Comment by kvistgaard** [comment]
It still doesn't work correctly. When switching to dark mode, a black icon remains black. Only after disabling and enabling the extension, it turns white.
